### ISSUE TITLE
installation instructions for Arch Linux are not correct

### ISSUE THREAD

**Issue by dvzrv** [gopasspw/gopasspw.github.io#5]
The installation instructions for Arch Linux should read `pacman -S gopass`.
`pacaur` is a [deprecated](https://github.com/rmarquis/pacaur), non-standard tool, that has nothing to do with the official Arch Linux distribution and should not be advertised in any way!
Please merge #2, which fixes this!

**Comment by metalmatze** [comment]
I've commented there. Thanks for the ping.
